# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-13 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='registered',
            field=models.DateField(default=datetime.date(2019, 8, 13)),
        ),
    ]
